# Generated by Django 4.2.5 on 2024-01-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=350, null=True, unique=True, verbose_name='текущая сессия для оплаты'),
        ),
    ]
